name: 'Security Considerations Action'
description: 'An action to check to make sure PR descriptions have "Security Considerations"'
author: 'Cloud.gov'
runs:
  using: 'node12'
  main: 'dist/index.js'
